name: Smoke testes - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTeste:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o projeto
      uses: actions/checkout@v4

    - name: Instalar java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'

    - name: Intalar Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Instalar o Chrome Driver
      uses: nanasess/setup-chromedriver@v2
      run: chromedriver --url-base=/wd/hub &

    - name: Executar testes
      uses: mvn test -Dtest=RunCucumberTeste -Dbrowser=chrome